version: '3.8'

services:
  bot:
    build: .
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - BOT_TOKEN=${BOT_TOKEN:?Discord Token is required}
    volumes:
      - karyl-chan-data:/usr/src/app/data

volumes:
  karyl-chan-data:
